### ISSUE TITLE
搜索框异常，能否把搜索语法简要展示在搜索窗口界面

### ISSUE THREAD

**Issue by Geo123abc** [choyy/simple-search#1]
“简易搜索”不简单啊。

看了下，可以极大提高搜索效率，但是也带来了一个问题，需要记忆一些命令，但是年纪大了，脑子不好使了，

所以能不能把搜索语法简单展示在搜索页面？比如  搜索界面“保存查询条件”、“清空查询条件”左边有一条空白（下图黄色条带区域），能不能放在这里？

使用官方daylight主题，搜索框显示异常，如下图（windows 10 ，siyuan v2.9.5版本，插件v0.0.1）

![](https://s3.bmp.ovh/imgs/2023/07/15/d1e5186d0e0f4d56.png)

**Comment by choyy** [comment]
黄色区域显示查询条件的
daylight主题搜索框显示异常我这里不能复现，你看看重新打开插件再ctrl+shift+i报啥错？

**Comment by Geo123abc** [comment]
> 黄色区域显示查询条件的 daylight主题搜索框显示异常我这里不能复现，你看看重新打开插件再ctrl+shift+i报啥错？

黄色区域是空白的，也没有输入框啊，现在被我PS了一下，我把查询窗口最下面的快捷键提示贴到了黄色区域，如果把这些提示换为“简易搜索”的就很适合像我这样的小白用户

![](https://s3.bmp.ovh/imgs/2023/07/15/e3bb217c6609ee69.png)



这是日志，算是bug吗？

![](https://s3.bmp.ovh/imgs/2023/07/15/be6a95f14c963495.png)

**Comment by choyy** [comment]
这是其他插件的报错，你把其他插件关了试试？

**Comment by choyy** [comment]
如果保存了查询条件会显示在白色区域的，那个区域不是没用的

**Comment by Geo123abc** [comment]
我新开了一个工作空间，只有简易搜索一个插件，主题daylight，这次确实没有报错了，但是还是无法正常显示

![](https://s3.bmp.ovh/imgs/2023/07/15/13e1458f4538c34f.png)

**Comment by Geo123abc** [comment]
> 

原来如此，我没保存过

那和思源自带的那个搜索提示放在一起，或者放在这个界面其它地方可以不？

**Comment by choyy** [comment]
看看这个设么结果
![image](https://github.com/choyy/simple-search/assets/68107073/67424bab-566e-4696-92e3-a587d10d5695)

![image](https://github.com/choyy/simple-search/assets/68107073/87c6b4bc-de52-4049-b445-f7942caff585)

**Comment by Geo123abc** [comment]
![](https://s3.bmp.ovh/imgs/2023/07/15/b518388ed858a598.png)

**Comment by choyy** [comment]
点它然后看看这里
> ![image](https://user-images.githubusercontent.com/68107073/253713008-87c6b4bc-de52-4049-b445-f7942caff585.png)

**Comment by Geo123abc** [comment]
录了个视频
https://wormhole.app/PZAeZ#tOC7grnH3V2RxDqHtLmS7Q

**Comment by choyy** [comment]
你打开文件位置，然后在`index.js`的第155行下面加上这句话，然后重启插件看看有没有报错输出
```
				console.log("搜索插件开始")
```
![image](https://github.com/choyy/simple-search/assets/68107073/d6965194-bd99-4942-bc9b-8dd3097f889c)
![image](https://github.com/choyy/simple-search/assets/68107073/507b8ed5-8542-420b-a3af-232f41b327df)

**Comment by Geo123abc** [comment]
刚才更新到  v0.0.2
插入上面那条代码

没有报错输出，控制台和刚才这个一样的
https://github.com/choyy/simple-search/issues/1#issuecomment-1636636152

我觉得是页面排版错位，功能性应该没问题，所以不会有bug报错

实在不行的话，再等等看，看看其他用户咋样，会不会一样的问题

**Comment by choyy** [comment]
如果没有输出“搜索插件开始”这句话说明有问题了，目前其他用户是能正常使用的

**Comment by Geo123abc** [comment]
> 如果没有输出“搜索插件开始”这句话说明有问题了，目前其他用户是能正常使用的

好的，谢谢，我再观察一下吧，辛苦了

**Comment by dacenss** [comment]
我也有这个问题，ctrl+p能正常使用，ctrl+f图标会重叠。

**Comment by choyy** [comment]
@dacenss 更新v0.0.3

**Comment by choyy** [comment]
@Geo123abc 你是这个情况吗，ctrl+p能用吗

> 我也有这个问题，ctrl+p能正常使用，ctrl+f图标会重叠。

**Comment by Geo123abc** [comment]
> 

我是都重叠，晚会我更新一下看看再反馈

**Comment by choyy** [comment]
> > 
> 
> 我是都重叠，晚会我更新一下看看再反馈

哦那还是有问题

**Comment by choyy** [comment]
> > 
> 
> 我是都重叠，晚会我更新一下看看再反馈

我大概知道了，你是不是修改了ctrl+p搜索的快捷键

**Comment by Geo123abc** [comment]
> > > 
> > 
> > 
> > 我是都重叠，晚会我更新一下看看再反馈
> 
> 我大概知道了，你是不是修改了ctrl+p搜索的快捷键

对我是修改了，我现在快捷键状态：
Ctrl+F：全局搜索
Ctrl+P：固定搜索
Ctrl+shift+G：搜索

其它快捷键也有改变，但是和插件有关的，好像只有这三个吧

上午测试时，我都是  Ctrl+F：全局搜索

**Comment by choyy** [comment]
那就是这个问题。。。

**Comment by Geo123abc** [comment]
> 

快捷键还影响啊？

**Comment by choyy** [comment]
@Geo123abc 更新v0.0.4
