### ISSUE TITLE
在当前文档搜索（ctrl F），用-s方式使用sql不生效，搜索所有文档（ctrl P）时却有效

### ISSUE THREAD

**Issue by Jiangshuon** [choyy/simple-search#11]
大佬这是bug吧

**Comment by choyy** [comment]
ctrl f界面确实是不生效的，只有在ctrl p界面才生效





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "choyy/simple-search"                                                                                    ***@***.***>;
发送时间: 2023年12月18日(星期一) 晚上9:49
收件人: ***@***.***>;
抄送: ***@***.***>;
主题: [choyy/simple-search] 在当前文档搜索（ctrl F），用-s方式使用sql不生效，搜索所有文档（ctrl P）时却有效 (Issue #11)



大佬这是bug吧
