### ISSUE TITLE
产生的bug

### ISSUE THREAD

**Issue by TinkMingKing** [choyy/simple-search#12]
https://github.com/siyuan-note/siyuan/issues/12126#issuecomment-2281596984

**Comment by choyy** [comment]
> 点击清空查询条件，红框里的搜索内容不会被清除

这个？这个确实，小问题

**Comment by TinkMingKing** [comment]
搜索条件无法保存也是

**Comment by choyy** [comment]
https://github.com/siyuan-note/siyuan/issues/12126#issuecomment-2277071513

这个不是，无论开不开插件都是这个结果
