### ISSUE TITLE
插件似乎不起作用？

### ISSUE THREAD

**Issue by HopeLHP** [choyy/simple-search#3]
下载插件-启动-siyuan重启后，输入内容似乎和siyuan的搜索没有区别？
`搜索关键词 -排除关键词`或者`搜索关键词 -d`都没有达到排除关键词搜索或仅搜索文档块的目的，

**Comment by choyy** [comment]
你是什么版本的思源，什么使用环境

**Comment by HopeLHP** [comment]
最新的2.9.6的思源，macos13.4.1 m1

**Comment by choyy** [comment]
你用ctrl shift i打开控制台，关了插件再重新打开看看有没有报错

**Comment by HopeLHP** [comment]
ctrl shift i没反应，是控制台还是活动监视器。不过我重装过插件，开开关关插件，都没反应还是自带的思源关键词搜索

**Comment by choyy** [comment]
在底部找到开发者选项按钮，点一下
