### ISSUE TITLE
能否打开搜索删除上次搜索的关键词残留

### ISSUE THREAD

**Issue by HopeLHP** [choyy/simple-search#6]
原装全局搜索下，上次搜索的关键词，在下次打开搜索会再次出现。能否实现打开搜索后重置搜索关键词？
这样就可以直接看到最新更新的块，而不是上次搜索乱七八糟的残留。

**Comment by choyy** [comment]
你若想打开搜索关键词为空，就打开插件目录，找到`index.js`这个文件，第201行给它注释掉就行了
```js
simpleSearchInput.value = data;
```

**Comment by HopeLHP** [comment]
这个会随插件更新而被覆盖吗，如果会被覆盖的话做成选项会不会好点。
同理，如果要做选项的话，或许可以再做几个选项丰富一下设置，例如定义“-”为其他符号，或者在文末还是文首输入“-xxx”。

**Comment by choyy** [comment]
会覆盖，选项没啥加的就不加了
“-xxx”可以在任意位置输入，但要用空格隔开
