### ISSUE TITLE
希望添加搜索条件时，可以不区分大小写

### ISSUE THREAD

**Issue by dandelion-wine** [choyy/simple-search#8]
如题，使用`科学 -k`搜索时，可以准确搜索到当前文档内，包含“科学”的块。但使用`科学 -K`时，会忽略过滤条件，依旧呈现所有包含“科学”的块。

使用场景是搜索一些英文符号时，如`CPU -K`，会下意识继续输入，不关闭大写锁定。
但此时大写的过滤条件会被忽略，要切回小写重新输入，比较麻烦。

感谢大佬带来这么好用的插件！

**Comment by dandelion-wine** [comment]
补：插件版本为集市最新，v0.0.9

**Comment by choyy** [comment]
大写以后有可能扩展其他功能，所以现在还是区分大小写
