### ISSUE TITLE
【BUG】使用过滤条件后，搜索结果异常

### ISSUE THREAD

**Issue by dandelion-wine** [choyy/simple-search#9]
更新思源到v2.10.13之后，用简易搜索的过滤条件“唤醒 -k”，搜索结果会异常地只显示一个奇怪的项。然后即使不使用过滤，只搜索“唤醒”，也会变成只显示那一个结果。
关掉插件，使用思源自带的搜索，没有出现这个情况。该BUG可以稳定复现，实测默认主题也会触发bug。
不确定其他过滤项会不会触发这个bug，没试。

录了复现bug的视频，不过我的github传不上来，已传到折腾群里，文件名为“2023.11.01 简易搜索插件bug”，上传日期也是2023.11.01

谢谢大佬带来这么好的插件！

**Comment by choyy** [comment]
如果现在没有问题了这个issue就先关了
